# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cxx-cmake"
BBFILE_PATTERN_meta-cxx-cmake = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cxx-cmake = "6"

LAYERDEPENDS_meta-cxx-cmake = "core openembedded-layer"
LAYERVERSION_meta-cxx-cmake = "1"
LAYERSERIES_COMPAT_meta-cxx-cmake = "wrynose"
